let config = {
	CLIENT_PROTOCOL_VERSION: 2,
	expectedMaxSkillLevel: 9,
	screenshotMode: 0,
	borderChunk: 5,
	barChunk: 5,
	barStyle: "Circle",
	darkBorders: 0,
	rgbBorders: false,
	noBorders: 0,
	colors: "classic",
	pointy: true,
	resolutionScale: 1,
	fontSizeBoost: 10,
	movementSmoothing: 1,
	fontStrokeRatio: 4.5,
	uiScale: 1.2,
	neon: 0,
	disableGameMessages: 0,
	chatMessageDuration: 5,
	roundUpgrades: 0,
	autoUpgrade: true,
	tintedDamage: true,
	lerpSize: true,
	glassMode: false,
	shaders: "Disabled",
	filterType: "none",
	tintedHealth: true,
	coloredHealthBars: false,
	deathAnimations: true,
	memory: 60,
	newPrediction: 0,
	prediction: 2,
	fontFamily: "Ubuntu"
};

export { config }